notes/notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.web.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/notes/web/urls.py
from django.urls import path

from notes.web.views import show_index, add_note, edit_note, delete_note, note_details, show_profile, create_profile, \
    delete_profile

urlpatterns = (
    path('', show_index, name='show index'),
    path('add/', add_note, name='add note'),
    path('edit/<int:pk>', edit_note, name='edit note'),
    path('delete/<int:pk>', delete_note, name='delete note'),
    path('details/<int:pk>', note_details, name='note details'),
    path('profile/', show_profile, name='profile'),
    path('profile/create/', create_profile, name='create profile'),
    path('delete profile/', delete_profile, name='delete profile'),


)

notes/notes/web/models.py
from django.db import models


class Profile(models.Model):
    FIRST_NAME_MAX_LENGTH = 20
    LAST_NAME_MAX_LENGTH = 20

    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
    )

    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
    )

    age = models.IntegerField()

    image_url = models.URLField()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'


class Note(models.Model):
    TITLE_MAX_LENGTH = 30

    title = models.CharField(
        max_length=TITLE_MAX_LENGTH,
    )
    image_url = models.URLField()

    content = models.TextField()

notes/notes/web/forms.py
from django import forms

from notes.web.models import Profile, Note
import os


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'age', 'image_url')
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'age': 'Age',
            'image_url': 'Link to Profile Image',
        }


class DeleteProfileForm(forms.ModelForm):

    def save(self, commit=True):
        image_path = self.instance.image.path
        self.instance.delete()
        Note.objects.all().delete()   # Delete all expenses when deleting the Profile
        os.remove(image_path)
        return self.instance

    class Meta:
        model = Profile
        fields = ()


class AddNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title','content', 'image_url')
        labels = {
            'title': 'Title',
            'content': 'Content',
            'image_url': 'Link to Image'
        }


class EditNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title','content', 'image_url')
        labels = {
            'title': 'Title',
            'content': 'Content',
            'image_url': 'Link to Image'
        }


class DeleteNoteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['disabled'] = 'disabled'  # Q&A session- to be confirmed how to do it
            field.required = False

    def save(self, commit=True):
        self.instance.delete()
        return self.instance

    class Meta:
        model = Note
        fields = ('title','content', 'image_url')
        labels = {
            'title': 'Title',
            'content': 'Content',
            'image_url': 'Link to Image'
        }

notes/notes/web/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect

from notes.web.forms import CreateProfileForm, AddNoteForm, EditNoteForm, DeleteNoteForm, DeleteProfileForm
from notes.web.models import Profile, Note


def get_profile():
    profiles = Profile.objects.all()
    if profiles:
        return profiles[0]

    return None


def show_index(request):
    profile = get_profile()
    if not profile:
        return redirect('create profile')
    notes = Note.objects.all()
    context = {
        'profile': profile,
        'notes': notes,
    }

    return render(request, 'home-with-profile.html', context)


def add_note(request):
    if request.method == 'POST':
        form = AddNoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('show index')
    else:
        form = AddNoteForm()
    context = {
        'form': form,
    }
    return render(request, 'note-create.html', context)


def edit_note(request, pk):
    note = Note.objects.get(pk=pk)
    if request.method == 'POST':
        form = EditNoteForm(request.POST, request.FILES, instance=note)
        if form.is_valid():
            form.save()
            return redirect('show index')
    else:
        form = EditNoteForm(instance=note)
    context = {
        'form': form,
        "note": note,
    }
    return render(request, 'note-edit.html', context)


def delete_note(request, pk):
    note = Note.objects.get(pk=pk)
    if request.method == 'POST':
        form = DeleteNoteForm(request.POST, request.FILES, instance=note)
        if form.is_valid():
            form.save()
            return redirect('show index')
    else:
        form = DeleteNoteForm(instance=note)
    context = {
        'form': form,
        'note': note,
    }
    return render(request, 'note-delete.html', context)


def note_details(request, pk):
    note = Note.objects.get(pk=pk)

    context = {
        'note': note,
    }

    return render(request, 'note-details.html', context)


def create_profile(request):
    if request.method == 'POST':
        form = CreateProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('show index')
    else:
        form = CreateProfileForm()
    context = {
        'form': form,
        'no_profile': True,
    }
    return render(request, 'home-no-profile.html', context)


def show_profile(request):
    profile = get_profile()
    notes = Note.objects.all()
    notes_count = len(notes)

    context = {
        'profile': profile,
        'notes': notes,
        'notes_count': notes_count,
    }
    return render(request, 'profile.html', context)


def delete_profile(request):
    instance_profile = get_profile()
    notes = Note.objects.all()
    Profile.delete(instance_profile)
    notes.delete()
    return redirect('create profile')

notes/templates/base/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="{% static 'images/note.png' %}" /></li>
                    <li><a href="{% url 'show index' %}">Notes</a></li>
                    <li class="right">
            {% if not no_profile %}
                        <a href="{% url 'add note' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
            {% endif %}
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            {% block page_content %}
            {% endblock %}
        </div>

        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
    </body>
</html>

notes/templates/home-no-profile.html
{% extends 'base/base.html' %}
{% block page_content %}
            <!--headings-->
            <h1>Enter Your Data</h1>
            <!--end headings-->

            <!--profile data form-->
            <div class="form">
                <form method="POST" action="{% url 'create profile' %}">
                    {{ form }}
                    {% csrf_token %}
{#                <input type="hidden" name="csrfmiddlewaretoken" value="97MmAxmrs7yPXUamEdIgRY80OHEP383f6VukAC6agPNIW60LqTcnIQlM6YCYPjc0" />#}
{#                    <label for="firstName">First Name</label>#}
{#                    <input type="text" name="first_name" maxlength="15" required="" id="id_first_name" />#}
{##}
{#                    <label for="lastName">Last Name</label>#}
{#                    <input type="text" name="last_name" maxlength="15" required="" id="id_last_name" />#}
{##}
{#                    <label for="age">Age</label>#}
{#                    <input type="number" name="age" required="" id="id_age" />#}
{##}
{#                    <label for="profilePhoto">Link to Profile Image</label>#}
{#                    <input type="url" name="profile_image" required="" id="id_image" />#}
{##}
                    <input type="submit" value="SUBMIT" />
                </form>
            </div>
            <!--end profile data form-->
{% endblock %}

notes/templates/home-with-profile.html
{% extends 'base/base.html' %}
{% block page_content %}

        <h1>My Notes</h1>
    {% if not notes %}
        <h2>There are no notes.</h2>
{#        <h2>Python Web Basics <img src="https://about.softuni.bg/Content/images/home-page/softuni-logo.svg" /></h2>#}
        <!--notes container-->

    {% else %}
    {% for note in notes %}
        <div class="note-container">

            <h2>{{ note.title}} <img src="{{ note.image_url }}" /></h2>
            <div class="right">
                <a class="button details" href="{% url 'note details' note.pk %}">Details</a>
                <a class="button edit" href="{% url 'edit note' note.pk %}">Edit</a>
                <a class="button delete" href="{% url 'delete note' note.pk %}">Delete</a>
            </div>

        </div>
    {% endfor %}



    {% endif %}

{% endblock %}

notes/templates/note-create.html
{% extends 'base/base.html' %}
{% block page_content %}
            <!--headings-->
            <h1>Add Note</h1>
            <!--headings-->

            <!--note data form-->
            <div class="form">
                <form method="POST" action="{% url 'add note' %}">
                    {{ form }}
                    {% csrf_token %}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" maxlength="50" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" maxlength="200" required="" id="id_image_url" />#}

                    <input type="submit" value="Publish" />
                </form>
            </div>
            <!--end note data form-->
{% endblock %}

notes/templates/note-delete.html
{% extends 'base/base.html' %}
{% block page_content %}
            <!--headings-->
            <h1>Delete Note</h1>
            <!--headings-->

            <!--note delete data form-->
            <div class="form">
                <form method="POST" action="{% url 'delete note' note.pk %}">
                    {{ form }}
                    {% csrf_token %}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" disabled="" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">#}
{#Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.#}
{##}
{#                    </textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" disabled="" required="" id="id_image_url" />#}

                    <input type="submit" value="Delete" />
                </form>
            </div>
            <!--end note delete data form-->
{% endblock %}

notes/templates/note-details.html
{% extends 'base/base.html' %}
{% block page_content %}
            <!--headings-->
            <h1>Note Details</h1>
            <!--headings-->

            <!--details note box-->
            <div class="note-details-container">
                <h2>Today's Tasks</h2>
                <img class="detail-img" src="{{ note.image_url}}" alt="/" />
                <div>
                    <p>Content</p>
                </div>
                <p>
                    {{ note.content }}
                </p>
                <div class="right">
                    <a class="button edit" href="{% url 'edit note' note.pk %}">Edit</a>
                    <a class="button delete" href="{% url 'delete note' note.pk %}">Delete</a>
                </div>
            </div>
            <!--end details note box-->
{% endblock %}

notes/templates/note-edit.html
{% extends 'base/base.html' %}
{% block page_content %}
            <!--headings-->
            <h1>Edit Note</h1>
            <!--headings-->

            <!--note edit data form-->
            <div class="form">
                <form method="POST" action="{% url 'edit note' note.pk %}">
                    {{ form }}
                    {% csrf_token %}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="E8qoLvlyiXBfE7NlcyWlXe1TMWV5qvo7BW8mLA5h6FQ8DjDKYeqsO6eF4dTecGxS" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" required="" id="id_description">Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.</textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" required="" id="id_image_url" />#}

                    <input type="submit" value="Edit" />
                </form>
            </div>
            <!--end note edit data form-->
{% endblock %}

notes/templates/profile.html
{% extends 'base/base.html' %}
{% block page_content %}
            <!--headings-->
            <h1>Your Profile</h1>
            <!--end headings-->

            <!--profile details container TODO-->
            <div class="note-container">
                <h2>
                    {{ profile.full_name }}
                    <img src="{{ profile.image_url }}" />
                </h2>
                <p>Age: {{ profile.age }}</p>
                <div>
                    <p>All notes: {{ notes_count }}</p>
                </div>
                <div class="right">
                    <a class="button delete" href="{% url 'delete profile' %}">Delete</a>
                </div>
            </div>
            <!--end profile details container-->
{% endblock %}